[package]
edition = "2021"
name = "identity-manager"
version = "0.1.0"

[dependencies]
serde = {version = "1", features = ["derive"]}
toml = "0.5.8"

core-objects = {path = "../common/core-objects"}

[dev-dependencies]
