[package]
name = "server-agent-api"
version = "0.1.0"
authors = ["Azure IoT Edge Devs"]
license = "MIT"
edition = "2021"

[dependencies]
core-objects = { path = "../core-objects" }
serde = "1"
serde_json = "1"

[features]
tests = []
