[package]
name = "core-objects"
version = "0.1.0"
authors = ["Azure IoT Edge Devs"]
license = "MIT"
edition = "2021"

[dependencies]
field_types = "1.1"
serde = { version = "1", features = ["derive"] }
strum_macros = "0.24"
serde_json = "1"

[features]
tests = []
