[workspace]
members = [
	"admin-api",	
	"catalog",
	"common",
	"config",	
	"key-manager",
	"key-store",
	"server-api",	
	"serverd",
	"trust-bundle-builder",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
