[workspace]
members = [
	"serverd",
	"common-admin-api",
	"common-server-api",
	"server-config",
	"admin-api",
	"server-api",
	"catalog",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
