socket_path = "api.sock"
trust_domain = "iotedge"

[jwt]
key_type = "ES256"
key_ttl = 300
ttl = 10

[trust-bundle]
refresh_hint = 1

[key-store]
type = "Disk"
[key-store.args]
key_base_path = "."

[catalog]
type = "Memory"

[server-agent-api]
bind_address = "0.0.0.0"
bind_port = 8443
