name: images

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "master"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: ACR login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build all
        uses: docker/build-push-action@v2
        with:
          context: .
          file: identities/docker/builder.dockerfile
          push: false
          tags: builder

      - name: Push Server
        uses: docker/build-push-action@v2
        with:
          context: .
          file: identities/docker/server.dockerfile
          push: true
          tags: ${{ secrets.ACR_REGISTRY }}/identity/server:${{ github.run_number }}, ${{ secrets.ACR_REGISTRY }}/identity/server:latest

      - name: Push Agent
        uses: docker/build-push-action@v2
        with:
          context: .
          file: identities/docker/agent.dockerfile
          push: true
          tags: ${{ secrets.ACR_REGISTRY }}/identity/agent:${{ github.run_number }}, ${{ secrets.ACR_REGISTRY }}/identity/agent:latest
