name: "test"

on:
  push: {}
  pull_request: {}

jobs:
  basic:
    runs-on: "ubuntu-18.04"

    strategy:
      fail-fast: false

      matrix:
        container_os:
          - "centos:7"
          - "debian:9-slim"
          - "debian:10-slim"
          - "ubuntu:18.04"
          - "ubuntu:20.04"
        arch:
          - "amd64"

    steps:
      - uses: "actions/checkout@v1"
        with:
          submodules: "recursive"
      - name: "Run"
        run: |
          docker run --rm \
            -v "$GITHUB_WORKSPACE:/src" \
            -e "ARCH=$ARCH" \
            "${{ matrix.container_os }}" \
            '/src/ci/test-basic.sh'
        env:
          ARCH: "${{ matrix.arch }}"

  codecov:
    runs-on: 'ubuntu-18.04'

    steps:
    - uses: 'actions/checkout@v1'
      with:
        submodules: 'recursive'

    - name: Run Code Coverage
      run: |
        mkdir $GITHUB_WORKSPACE/coverage
        # cargo-tarpaulin needs a privileged container because it needs to disable ASLR for its instrumentation,
        # for which it uses seccomp.
        docker run --rm \
          -v "$GITHUB_WORKSPACE:/src" \
          -e "ARCH=$ARCH" \
          --privileged \
          --name "code-cov" \
          "ubuntu:18.04" \
          '/src/ci/code-coverage.sh'
        sudo chown -R runner:docker $GITHUB_WORKSPACE/coverage
      env:
        ARCH: 'amd64'

    - name: Code Coverage Report
      uses: romeovs/lcov-reporter-action@v0.3.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        lcov-file: ./coverage/lcov.info
        filter-changed-files: true
